[package]
name = "tidy"
version = "0.1.0"
authors = ["Hristo Filaretov <h.filaretov@campus.tu-berlin.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
walkdir = "2"